[package]
name = "coli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.4", features = ["derive"] }
owo-colors = "3.5.0"
palette = "0.6.1"
rand = "0.8.5"
hex = "0.4"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }

[profile.release]
lto = true
codegen-units = 1
