on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.friendly }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            friendly: Windows
          - target: x86_64-unknown-linux-musl
            friendly: Linux
          - target: x86_64-apple-darwin
            friendly: Mac
            
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Prepare the toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true

      - name: Build the project
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --verbose -Z unstable-options --out-dir=build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.friendly }}
          path: build
